# Spring boot application
spring:
  application:
    name: myProject-service-sso
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.1.7:26379, 192.168.1.7:26380, 192.168.1.7:26381
    timeout: 3000
  session:
    store-type: redis
server:
  port: 8504

# Services Versions
services:
  versions:
    redis:
      v1: 1.0.0