# Spring boot application
spring:
  application:
    name: myProject-service-upload
server:
  port: 8888

fastdfs.base.url: http://47.98.131.180:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 47.98.131.180:22122